import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface MarkdownRendererProps {
  content: string;
  className?: string;
  citationsList?: Array<{ code: string; title: string }>;
}

/**
 * Cleans up raw LaTeX artifacts often generated by LLMs (e.g., $115.0\text{ g} \rightarrow \rho = 0.3485\text{ g/ml}$)
 * into clean, readable scientific unicode text.
 */
function cleanLatexAndMath(rawText: string): string {
  if (!rawText) return '';

  let text = rawText;

  // Fix escaped percentage or dollar signs
  text = text.replace(/\\%/g, '%');
  text = text.replace(/\\\$/g, '$');

  // Replace common LaTeX Greek letters & symbols
  text = text.replace(/\\rho/g, 'ρ');
  text = text.replace(/\\rightarrow/g, '→');
  text = text.replace(/\\leftarrow/g, '←');
  text = text.replace(/\\ge/g, '≥');
  text = text.replace(/\\le/g, '≤');
  text = text.replace(/\\pm/g, '±');
  text = text.replace(/\\times/g, '×');
  text = text.replace(/\\Delta/g, 'Δ');
  text = text.replace(/\\mu/g, 'µ');
  text = text.replace(/\\alpha/g, 'α');
  text = text.replace(/\\beta/g, 'β');
  text = text.replace(/\\gamma/g, 'γ');
  text = text.replace(/\\approx/g, '≈');
  text = text.replace(/\\neq/g, '≠');

  // Replace \text{...} or \mathrm{...} inside formulas with plain text
  text = text.replace(/\\text\{([^}]+)\}/g, '$1');
  text = text.replace(/\\mathrm\{([^}]+)\}/g, '$1');
  text = text.replace(/\\mathbf\{([^}]+)\}/g, '**$1**');
  text = text.replace(/\\mathit\{([^}]+)\}/g, '*$1*');

  // Replace \frac{a}{b} with a / b
  text = text.replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '$1 / $2');

  // Clean unrendered math enclosing dollars like $115.0 g → ρ = 0.3485 g/ml$ or $$formula$$
  // If it contains dollar signs, unwrap them cleanly while preserving inner spacing
  text = text.replace(/\$\$([^$]+)\$\$/g, '$1');
  text = text.replace(/\$([^$]+)\$/g, '$1');

  return text;
}

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({
  content,
  className = '',
}) => {
  const sanitizedContent = cleanLatexAndMath(content);

  return (
    <div className={`prose prose-invert max-w-none text-stone-200 text-xs sm:text-sm leading-relaxed ${className}`}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          h1: ({ children }) => (
            <h1 className="text-base sm:text-lg font-bold font-serif text-white mt-4 mb-2 pb-1 border-b border-[#262f3e] first:mt-0">
              {children}
            </h1>
          ),
          h2: ({ children }) => (
            <h2 className="text-sm sm:text-base font-bold font-serif text-emerald-300 mt-3.5 mb-1.5 first:mt-0 flex items-center space-x-2">
              <span className="w-1.5 h-3.5 bg-emerald-500 rounded-xs inline-block shrink-0" />
              <span>{children}</span>
            </h2>
          ),
          h3: ({ children }) => (
            <h3 className="text-xs sm:text-sm font-semibold text-emerald-400 mt-3 mb-1 font-sans flex items-center space-x-1.5">
              <span>{children}</span>
            </h3>
          ),
          h4: ({ children }) => (
            <h4 className="text-xs font-semibold text-stone-200 mt-2 mb-1 font-sans">
              {children}
            </h4>
          ),
          p: ({ children }) => (
            <p className="mb-2.5 last:mb-0 leading-relaxed font-sans text-stone-200">
              {children}
            </p>
          ),
          ul: ({ children }) => (
            <ul className="list-disc list-outside ml-4 sm:ml-5 space-y-1.5 my-2.5 text-stone-300">
              {children}
            </ul>
          ),
          ol: ({ children }) => (
            <ol className="list-decimal list-outside ml-4 sm:ml-5 space-y-1.5 my-2.5 text-stone-300">
              {children}
            </ol>
          ),
          li: ({ children }) => (
            <li className="leading-relaxed pl-1 marker:text-emerald-400 font-sans">
              {children}
            </li>
          ),
          strong: ({ children }) => {
            const text = String(children);
            // Highlight citation codes like [REF-001]
            if (/^\[REF-\d{3}\]/.test(text)) {
              return (
                <span className="inline-flex items-center px-1.5 py-0.5 rounded-md bg-emerald-950/80 text-emerald-300 border border-emerald-700/60 text-[11px] font-sans font-semibold mx-0.5 whitespace-nowrap shadow-xs">
                  {children}
                </span>
              );
            }
            return <strong className="font-semibold text-white font-sans">{children}</strong>;
          },
          em: ({ children }) => (
            <em className="italic text-stone-300">{children}</em>
          ),
          blockquote: ({ children }) => (
            <blockquote className="my-3 pl-3.5 py-1.5 border-l-2 border-emerald-500 bg-[#121824] rounded-r-lg text-stone-300 text-xs sm:text-[13px] font-sans">
              {children}
            </blockquote>
          ),
          code: ({ children }) => (
            <code className="px-1.5 py-0.5 rounded bg-[#1c2230] text-emerald-300 text-[11px] font-mono border border-[#2b3345]">
              {children}
            </code>
          ),
          pre: ({ children }) => (
            <pre className="p-3 my-2.5 rounded-xl bg-[#0d1017] border border-[#232936] text-stone-200 text-xs overflow-x-auto font-mono">
              {children}
            </pre>
          ),
          table: ({ children }) => (
            <div className="my-3 overflow-x-auto rounded-xl border border-[#232936]">
              <table className="w-full text-left text-xs border-collapse font-sans">{children}</table>
            </div>
          ),
          th: ({ children }) => (
            <th className="bg-[#141822] p-2.5 font-semibold text-emerald-300 border-b border-[#232936]">
              {children}
            </th>
          ),
          td: ({ children }) => (
            <td className="p-2.5 border-b border-[#1b202c] text-stone-300">
              {children}
            </td>
          ),
          hr: () => <hr className="my-4 border-[#232936]" />,
        }}
      >
        {sanitizedContent}
      </ReactMarkdown>
    </div>
  );
};
